# Generated by Django 5.1.5 on 2025-01-16 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startingPlayerNum', models.IntegerField(default=0, verbose_name='공격 숫자')),
                ('defendingPlayerNum', models.IntegerField(default=0, verbose_name='반격 숫자')),
                ('status', models.CharField(choices=[('ongoing', '진행중'), ('end', '종료됨')], default='ongoing', max_length=50, verbose_name='게임 상태')),
                ('winner', models.CharField(blank=True, choices=[('starting', '공격 유저 승리'), ('defending', '방어 유저 승리'), ('draw', '무승부')], max_length=50, null=True, verbose_name='승자')),
                ('defendingPlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_defended', to=settings.AUTH_USER_MODEL, verbose_name='공격 받은 유저')),
                ('startingPlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_started', to=settings.AUTH_USER_MODEL, verbose_name='공격한 유저')),
            ],
        ),
    ]
