# Generated by Django 5.1.5 on 2025-01-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('ongoing', '진행중 ...'), ('end', '결과 :')], default='ongoing', max_length=50, verbose_name='게임 상태'),
        ),
    ]
